name: Build and Push RabbitMQ Buildfarm Worker Images

on:
  push:
    branches:
      - rabbitmq-2.8.0
jobs:
  build:
    name: Build RabbitMQ Buildfarm Worker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Mount Repo Cache
        uses: actions/cache@v4.0.1
        with:
          path: "/home/runner/repo-cache/"
          key: ${{ runner.os }}-repo-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-repo-cache-

      - name: Mount Disk Cache
        uses: actions/cache@v4.0.1
        with:
          path: "/home/runner/disk-cache/"
          key: ${{ runner.os }}-disk-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-disk-cache-

      - name: Build Docker image
        run: |
          bazel run \
            --repository_cache=/home/runner/repo-cache/ \
            --disk_cache=/home/runner/disk-cache/ \
            --color=yes \
            //rabbitmq:publish-buildfarm-shard-worker-rabbitmq-server-buildenv
